name: ba_zi_energy
description: energy data classes for ba zi
version: 0.0.1
homepage:

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:

dev_dependencies:
  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0
